version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # volumes:
    #   - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - confluent
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-setup:
    image: minio/mc
    container_name: minio_setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc config --quiet host add dmlminio http://minio:9000 minioadmin minioadmin
      /usr/bin/mc mb --quiet dmlminio/bronze;
      /usr/bin/mc mb --quiet dmlminio/storage;
      /usr/bin/mc mb --quiet dmlminio/bronze/_checkpoints/testing_data_streaming;
      exit 0;
      "
    networks:
      - confluent

# volumes:
#   minio_data:

networks:
  confluent:
    external: true